(defpackage :conv
  (:use :cl)
  (:export "STRING!" "STRING?" "INTEGER!" "INTEGER?" "MONEY!" "MONEY?" "BOOLEAN!" "FLOAT!" "FLOAT?"))

(defpackage :english 
  (:use :cl)
  (:export "VOWELP" "PLURALISE-WORD" "FORMAT-PHONE-NUMBER" "NORMALISE-PHONE-NUMBER" "FORMAT-ABN" "MAKE-ABN" 
           "MAKE-PHONE-NUMBER" "MAKE-EMAIL-ADDRESS"))

(defpackage :utils
  (:use :cl)
  (:export "CASE*" "STRCAT" "STRCAT-ADJACENT" "JOIN" "LEFT-PAD" "URLIFY" "RANDOM-ALPHA-ASCII-STRING" "STARTS-WITH" "ENDS-WITH" "&" "&&" "MATCH"
           "COMPOSE" "PARTIAL" "PARTIAL*" "REVERSE-C-BYTE-ORDER" "GROUP*" "FLATTEN" "INTERSPERSE" "MKLIST" "UNCONS" "NSUBSEQ"))

